### ISSUE TITLE
你好，按照你的方式怎样才能让水印显示出来

### ISSUE THREAD

**Issue by abcnxy** [hustcc/alimask#3]
如题

**Comment by hustcc** [comment]
可以参考项目网站的做法：http://git.hust.cc/alimask/

具体代码为：https://github.com/hustcc/alimask/blob/master/index.html#L67

**Comment by abcnxy** [comment]
你好，我的意思是:  截图后怎么处理，才能让隐形水印 显示出来

**Comment by hustcc** [comment]
截图里面就有背景图啊😱

**Comment by abcnxy** [comment]
额，难道这种水印方式不是隐藏水印吗？   就是透明度为0，截图后通过PS处理或者什么其他方式 能让隐藏水印显示出来？

**Comment by hustcc** [comment]
不是，阿里内网网站就是使用这种背景图片作为水印的，并不是隐藏的。

**Comment by abcnxy** [comment]
谢谢你的耐心答复
