### ISSUE TITLE
水印控件使用中遇到的问题

### ISSUE THREAD

**Issue by eatmyball** [hustcc/alimask#4]
@hustcc 您好，非常感谢您提供的组件，目前我们项目中使用控件遇到的问题，和您一起分享一下。

1. 如果水印用在表单或者列表等需要交互的场景下，放在背景上可能会被显示的数据遮挡。
2. 如果水印遮罩在数据上，又会影响到用户的交互行为，例如点击、列表滑动等事件，不知道您这边有什么解决方法没有

如果您能够回复的话，非常感谢！

**Comment by hustcc** [comment]
不设置Css背景颜色，设置 div 背景图为生成的图片 base64。

**Comment by eatmyball** [comment]
@hustcc 非常感谢，已经解决了。使用一个div遮罩在整个页面上，postion为fixed，pointer-events为none就可以忽略掉遮罩层的点击事件。
