### ISSUE TITLE
请问如果有办法修改整个背景图的颜色吗？

### ISSUE THREAD

**Issue by zhanzekun** [hustcc/alimask#7]
因为看到组件内只有修改字体颜色的参数
如果我想修改整个背景图的颜色有办法吗？

**Comment by hustcc** [comment]
背景颜色是透明的，难道还需要让背景不是透明的？

**Comment by zhanzekun** [comment]
HHHH~ 可能是我的问题，我修改了一下您的源码然后work了~
我的body标签本来就设了背景色~所以被设置成透明后出了问题
只要第一次ctx.fillStyle改成用户当前标签背景色就可以了~

ctx.globalAlpha = 1; 
    ctx.fillStyle = 这里改成我的背景色了
    ctx.fillRect(0, 0, width, height);

    ctx.globalAlpha= options.alpha; 
    ctx.fillStyle = options.color;
    ctx.font = options.font;

**Comment by hustcc** [comment]
是的，但是不知道为啥需要这个背景色，本项目就不加这个了😣

**Comment by hustcc** [comment]
是的，但是不知道为啥需要这个背景色，本项目就不加这个了😣
